pipeline:
  name: Manisha
  identifier: Manisha
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ManishaGithub
        repoName: ff-golang-server-sdk
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "delegate is up and running"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: build stage
        identifier: build_stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: dotNetBuild
                  identifier: dotNetBuild
                  spec:
                    shell: Sh
                    command: echo "starting the build"
        delegateSelectors:
          - docker-delegate
          - docker-delegate-tx
          - linux-delegate-tx
          - linux-tx
