pipeline:
  name: Manisha
  identifier: Manisha
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ManishaGithub
        repoName: ff-golang-server-sdk
        build: <+input>
  stages:
    - stage:
        name: build stage
        identifier: build_stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: dotNetBuild
                  identifier: dotNetBuild
                  spec:
                    shell: Sh
                    command: echo "starting the build"
        delegateSelectors:
          - linux-delegate-tx-project
          - linux-porj
