openapi: 3.0.0
info:
  title: Harness SDK Test Wrapper API
  version: 1.0.0
  contact:
    name: Feature Flag - developers
    url: 'https://www.harness.io'
    email: cf@harness.io
servers:
  - url: /api/1.0
    description: no host specified
  - url: 'http://localhost:3001/api/1.0'
    description: FF Test Wrappers
paths:
  /check_flag:
    post:
      summary: Check the value of a flag
      operationId: GetFlagValue
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlagCheckResponse'
        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlagCheckBody'
  /ping:
    get:
      summary: Check the system is up
      operationId: Ping
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PongResponse'
        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
components:
  schemas:
    FlagCheckBody:
      type: object
      description: Request to check flag in SDK
      properties:
        flag_key:
          type: string
          example: my_flag_key
        flag_kind:
          type: string
          example: json
        target:
          type: object
          properties:
            name:
              type: string
              example: Jane
            email:
              type: string
              example: jane@example.com
            region:
              type: string
              example: Europe
      required:
        - flag_key
        - flag_kind
    FlagCheckResponse:
      type: object
      description: Response to flag check in SDK
      properties:
        flag_key:
          type: string
        flag_value:
          type: string
      required:
        - flag_key
        - flag_value
    PongResponse:
      type: object
      description: Response to Ping
      properties:
        pong:
          type: boolean
      required:
        - pong
    ErrorResponse:
      type: object
      description: Error Status for wrapper
      properties:
        error_message:
          type: string
      required:
        - error_message
